name: Run AoC
on: [push]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: coretto
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute tests
      run: ./gradlew test
    
    - name: Run
      run: ./gradlew run
